### ISSUE TITLE
列拖拽异常,无法拖拽

### ISSUE THREAD

**Issue by hn7830626** [surely-vue/table#102]
根据官方提供的示例分析: 每个column需要加上key 才能进行拖拽; **之前只要设置columnDrag = true就可以实现拖拽**;现在install后就无法拖拽; 
官方示例如图:
不可拖拽列设置:
![image](https://user-images.githubusercontent.com/42940041/205863730-ae3e89d0-4752-47c1-b799-2ba54be22f0f.png)
![1670316423758](https://user-images.githubusercontent.com/42940041/205863743-c15baf98-7b61-4368-b734-c56a1377d2c8.png)

可拖拽列设置:
![1670316459335](https://user-images.githubusercontent.com/42940041/205865713-d4fae804-f959-4b74-8ffb-d5d5ce3febb5.png)

**Comment by tangjinzhou** [comment]
啥意思，没懂，是有问题还是没问题

**Comment by hn7830626** [comment]
> 啥意思，没懂，是有问题还是没问题
意思是在 s-table 上设置 columnDrag = true,列不能拖拽了,需要给相应的拖拽列加上key值; 之前不用设置列的key值就可以进行拖拽

**Comment by hn7830626** [comment]
能否设置columnDrag = true;列就可以拖拽了

**Comment by tangjinzhou** [comment]
不可以，需要 key
之前不加key是会有其它问题的
