### ISSUE TITLE
getCheckboxProps只有首次会触发，参数修改不会触发函数

### ISSUE THREAD

**Issue by wHannnnnn** [surely-vue/table#107]

**Comment by tangjinzhou** [comment]
提供复现吧，我也不知道你改的啥

数据驱动，改参数当然不会触发 render，我说的参数不知道是不是你说的参数

**Comment by wHannnnnn** [comment]
> 提供复现吧，我也不知道你改的啥
> 
> 数据驱动，改参数当然不会触发 render，我说的参数不知道是不是你说的参数

https://codesandbox.io/s/gallant-water-37le5n?file=/src/App.vue

**Comment by wHannnnnn** [comment]
>
