### ISSUE TITLE
全局修改默认值

### ISSUE THREAD

**Issue by YongTQ** [surely-vue/table#108]
请问，当我全局引入Surely Table时，我想设置一些默认值，例如我想表头增加默认底色或设置居中，且在系统中能随时修改这种默认值，目前有什么参数或方法吗？

**Comment by tangjinzhou** [comment]
底色你需要覆盖 less 变量，或者直接 css 覆盖，居中本身也可以使用 css ，不过这个 column 有一个 align: 'center' 可以配置

**Comment by TengQQQ** [comment]
好的，非常感谢，本来想尝试使用重置default的方法，但这种方法一旦使用这个api默认就会失效了。看来只能通过css覆盖的方式实现了，根据配置去实现动态的覆盖surely-table-header-cell
