### ISSUE TITLE
hover 表格时，会触发组件的重新渲染

### ISSUE THREAD

**Issue by hnzhangyang** [surely-vue/table#110]
问题重现：
版本：2.5.4  
实例：使用的官方的实例（https://www.surely.cool/doc/basic#basic）

问题描述：
在表格上 hover 每一行时（别的什么都不干），通过 performance 记录下来每次 hover 都会导致 componentUpdateFn 的触发（组件重新渲染）。这个问题在普通表格使用中对性能影响不明显， 但是在深度很深的树形表格中使用起来就非常卡。目前有什么方法能优化下这个部分吗？

![image](https://user-images.githubusercontent.com/20033699/216221631-da18cd5c-50d4-4770-ab14-980fded36152.png)

**Comment by tangjinzhou** [comment]
等下个版本吧，有方案解决 hover 问题了

**Comment by hnzhangyang** [comment]
好的，请问下个版本大概什么时候发布？

**Comment by tangjinzhou** [comment]
这周吧，在考虑是否发大版本，破坏性更新

**Comment by hnzhangyang** [comment]
好的，谢谢。更新后我再试下

**Comment by tangjinzhou** [comment]
3.0 试试

**Comment by hnzhangyang** [comment]
3.0 测试没这个问题了，谢谢~
