### ISSUE TITLE
屏幕分辨率设置为125%时，表格出现横向滚动条时候，滚动高度没达到表格设置的 scroll-y 的高度，也会出现纵向滚动条

### ISSUE THREAD

**Issue by ZzNb0813** [surely-vue/table#113]
屏幕分辨率设置为125%时，表格出现横向滚动条时候，滚动高度没达到表格设置的 scroll-y 的高度，也会出现纵向滚动条
列如：设置的滚动高度为 500   有横向滚动条时候，只有一条数据也会出现纵向的滚动条

**Comment by ZzNb0813** [comment]
这个问题大概啥时候优化呢?

**Comment by ZzNb0813** [comment]
@tangjinzhou  您好，这个问题一般啥时候会优化呢？现在笔记本电脑一般的推荐分辨率就是125%，出现滚动条挺影响效果的

**Comment by tangjinzhou** [comment]
方便提交一个在线示例吗

**Comment by ZzNb0813** [comment]
[https://codesandbox.io/s/silly-danilo-xyn7ew?file=/src/App.vue](url)

**Comment by ZzNb0813** [comment]
[https://codesandbox.io/s/silly-danilo-xyn7ew?file=/src/App.vue](示列)

**Comment by ZzNb0813** [comment]
[https://codesandbox.io/s/silly-danilo-xyn7ew?file=/src/App.vue](在线示列)

**Comment by ZzNb0813** [comment]
[在线示例](https://codesandbox.io/s/silly-danilo-xyn7ew?file=/src/App.vue)

**Comment by ZzNb0813** [comment]
[在线示例](https://codesandbox.io/s/silly-danilo-xyn7ew?file=/src/App.vue)  屏幕分辨率125%，系统windows10，应该其他windows也一样，mac 目前没复现

**Comment by tangjinzhou** [comment]
周末发版

**Comment by tangjinzhou** [comment]
update to 3.0.1
