### ISSUE TITLE
我们在开发内网管理系统,规模较小,还没有任何收入来源,期望可以“免费”得到一个全匹配版本的surely-table无水印,我们可以定期赞助

### ISSUE THREAD

**Issue by cheng-io** [surely-vue/table#114]

**Comment by cheng-io** [comment]
跟公司沟通过,公司目前暂时没有投入的打算,开发周期还处于比较紧张的阶段,我的意思先用,而领导认为先抓紧开发业务,而不是试用surely-vue,承担风险.但我看到surely-vue具有无限潜力

**Comment by tangjinzhou** [comment]
感谢认可，但是很抱歉，无法免费提供授权。
你可以直接使用 antdv 自带的免费版本就好了
