### ISSUE TITLE
defaultExpandAllRows 属性设置问题

### ISSUE THREAD

**Issue by yushungong** [surely-vue/table#115]
在 expandedRowKeys 设置为一个空数组的情况下，:defaultExpandAllRows="true" 失效。

样例地址：
https://codesandbox.io/s/wispy-fog-wv6qwb?file=/src/App.vue:3119-3134

**Comment by tangjinzhou** [comment]
expandedRowKeys 和 defaultExpandAllRows 冲突了，expandedRowKeys 优先级更高
另外 defaultExpandAllRows 只在初始化时首次生效

**Comment by yushungong** [comment]
可以调高&nbsp;defaultExpandAllRows&nbsp;的优先级吗，因为这两个属性我都需要使用
&nbsp;


龚先生
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月3日(星期五) 上午9:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [surely-vue/table] defaultExpandAllRows 属性设置问题 (Issue #115)





 
expandedRowKeys 和 defaultExpandAllRows 冲突了，expandedRowKeys 优先级更高
 另外 defaultExpandAllRows 只在初始化时首次生效

**Comment by tangjinzhou** [comment]
？
表达有误，不是优先级问题，是冲突问题。

做不到调整优先级
