### ISSUE TITLE
更新版本到3.0.1后，expand方法未触发

### ISSUE THREAD

**Issue by YongTQ** [surely-vue/table#118]
使用了最简单的表格，代码如下：
`<s-table
    :columns="[{title: '输入框', dataIndex: 'name',}]"
    rowKey="id"
    :dataSource="[{id: 1,name: '001',children: [{id: 2,name: '001-1'}]}]"
    size="small"
    :expandedRowKeys="expandedRowKeys"
    @expand="expand"
  >
  </s-table>

const expandedRowKeys = ref<any[]>([]);
const expand = (expanded: any, record: any) => {
  debugger
};
`

点击展开图标未进入debugger，还原版本到2.5.4可以触发，请检查一下吧

**Comment by tangjinzhou** [comment]
update to 3.0.2
