### ISSUE TITLE
动态把表格列隐藏，然后再进行列的拖拽会导致报错

### ISSUE THREAD

**Issue by xiaobaiku** [surely-vue/table#128]
surelyTable版本：2.5.0

这里的隐藏指的是重新生成一个不包含某列的columns数据源

![image](https://user-images.githubusercontent.com/31175506/230845207-8c4a0aa3-8e42-4ca4-aeb9-582d5566bd6c.png)

**Comment by tangjinzhou** [comment]
参考这个提供一个在线复现示例吧   https://codesandbox.io/s/aged-brook-xzlwmv

**Comment by xiaobaiku** [comment]
感谢回复！

做了最小化测试，没有发现问题。因该是我自己的问题，已经通过调整写法来避免这个问题
