### ISSUE TITLE
通过 resizable 拖拽的列宽度， 改变 columns  数据，拖拽的列宽就会还原

### ISSUE THREAD

**Issue by ZzNb0813** [surely-vue/table#134]
通过 resizable 拖拽的列宽度， 改变 columns  数据，拖拽的列宽就会还原， 本身列宽 为100  拖拽后变成200， 改变了columns  ，列宽会还原成100

**Comment by tangjinzhou** [comment]
哪个版本，提供一个在线示例直接帮你调试吧

**Comment by ZzNb0813** [comment]
本地问题
