### ISSUE TITLE
这个是在想适配移动端发现的。当屏幕变小以后，如果最右边的列被fix了，table设置的:scroll x 小于总的width。最后一列width会失效 。问题已经解决，只是想知道为什么会这样

### ISSUE THREAD

**Issue by chenbaicheng** [surely-vue/table#136]
这里错误前提都是，1.谷歌浏览器的开发者工具，手机模拟仿真。2。scroll设置的 x  大于   所有的列的width总和。

过程：因为有很多页面，我在发现屏幕小了，最后一列实在太宽了，所以打算所有页面从200变成110，但是问题来了，有些页面正常，有些页面最后一列还是很宽，连第一列也挡住了。排除了几个小时，想到全身发热了，有点想吐。突然想到，好像每个页面的列数都不一样，这些页面唯一的不同，立即拿出计算器，将正常的页面总列宽算一下，不正常页面的列宽算一下，果然不正常的，都是小于scroll设置的 x  

先说我解决方法
1.最简单的办法是在最后一列，加上resizable
var columns = [
 {
	"title": "操作",
	"dataIndex": "operation",
	"width": 110,
	"fixed": "right",
	"resizable": true
}];
不过这里会有个显示问题，在手机屏幕确实是按照变小了，但是因为现在是可以resiable的  ，所以最后往右拖，将它拉宽。然后滚动滚动条左右拉，最后一列会被拖到左边，然后不见了，效果就好像最后一列后面还有很多空白列，当然往回拖，最后一列还在，就是空白地方很多。
2. 第二种解决办法，就是先计算总列宽的大小，再设置 scroll的x大小  ,原本我是 x是1000 ，因为现在总列宽大概是860，现在设置成 800就正常。
<s-table :columns="columns" :row-key="record => record.id" :data-source="dataSource" :pagination="pagination"
		:loading="loading" @change="handleTableChange" :scroll="{y:'calc(98vh - 150px)',x: 800}" column-drag></s-table>

好奇其中的原因。

额外的问题，这个我确实是无法复现，因为所有页面都不生效  也是关于响应式的  就是column里面设置  "responsive": ["lg"]，无效。
var columns = [
 {
	"title": "操作",
	"dataIndex": "operation",
	"width": 110,
	"fixed": "right",
	"responsive": ["lg"]
}];
这个其实是我一开始的想法，我的构想是，如果屏幕变小就直接隐藏那些列，只保留一列。后来发现无效，才想缩小最后一列的宽度，左右各fix一列，适配手机界面。这样iphon se小屏幕也能操作十多列的表格，反正可以滚动。谢谢  五一快乐

**Comment by chenbaicheng** [comment]
使用"resizable": true  后，多出来的空白，应该就是   scroll的x  减去  所有列总列宽  多出来的地方。我刚刚试了一下，它们差值越大，后面空白越长，

**Comment by tangjinzhou** [comment]
如果所有列都设置了宽度，那么加起来又恰好小于 X，实际上是剩余 一定宽度的，那么剩余的宽度加在哪一列上是个问题，现在的方案是加到了最后一列上上面。这剩余的宽度不管怎么处理都不完美。
你可以根据业务情况，计算一个 X 比较靠谱。

**Comment by chenbaicheng** [comment]
> 如果所有列都设置了宽度，那么加起来又恰好小于 X，实际上是剩余 一定宽度的，那么剩余的宽度加在哪一列上是个问题，现在的方案是加到了最后一列上上面。这剩余的宽度不管怎么处理都不完美。 你可以根据业务情况，计算一个 X 比较靠谱。

嗯嗯  其实这个屏幕只要不缩小，完全看不出来的，只是我突然要适配小屏幕，是我的问题。另外一个小问题  responsive 属性无效，是我用法错了。。还是我没有成功触发。求指导 谢谢·

**Comment by chenbaicheng** [comment]
> 
有个新问题   列变小以后  点击弹窗也变形了   
![image](https://github.com/surely-vue/table/assets/16386693/f9a46294-d5b9-42cb-8613-e7040961886d)

**Comment by chenbaicheng** [comment]
好吧这个不是 surly vue的问题  有哪个亲能伸出援手

**Comment by tangjinzhou** [comment]
这个你可以去 ant-design-vue 那边提，目测.ant-popover-buttons 设置个大一点的宽度是可以解决的

但不完美，右侧区域不够放下两个按钮了，你可以根据不同屏幕大小使用不同的  placement
