### ISSUE TITLE
对于复选框全选勾选的问题

### ISSUE THREAD

**Issue by YYDee-0920** [surely-vue/table#137]
对STable设置可选择，但是因为一些业务逻辑，导致某些行不能够选择。对于父子结构数据，因父子勾选联动，会导致全选时将不可选择的一起勾选上（猜测可能是勾选了父的默认行为），但当取消全选时，又无法取消不可选择的，导致父同时无法取消（猜测因子被勾选，父也选中），如图
![STable全选问题](https://github.com/surely-vue/table/assets/69885396/e13b48df-a1a7-432f-bc69-49fad35f78c3)

**Comment by tangjinzhou** [comment]
![image](https://github.com/surely-vue/table/assets/6937879/7252ec1b-980a-4d16-9999-a5626c1ba75f)
官网示例没有问题的，https://www.surely.cool/doc/selection#row-selection

可以看下示例，如果还有问题，可以提交一个在线示例

**Comment by YYDee-0920** [comment]
很抱歉没有提供在线示例，在本地写了个demo，还是能复现出来的，代码如下：

<template>
  <s-table
    :columns="[{ title: '输入框', dataIndex: 'name' }]"
    rowKey="id"
    :dataSource="dataSource"
    size="small"
    :row-selection="rowSelection"
    defaultExpandAllRows
  >
  </s-table>
</template>
<script setup lang="tsx">
const dataSource = ref([
  { id: 1, name: '001', children: [{ id: 2, name: '001-1' }] },
  { id: 3, name: '002', children: [{ id: 4, name: '002-1' }] },
]);
const rowSelection: STableProps['rowSelection'] = {
  checkStrictly: false,
  onChange: (selectedRowKeys: string[], selectedRows: DataType[]) => {
    console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
  },
  getCheckboxProps: (record: DataType) => ({
    disabled: record.id === 4, // Column configuration not to be checked
  }),
};
</script>

**Comment by YYDee-0920** [comment]
> ![image](https://user-images.githubusercontent.com/6937879/238226904-7252ec1b-980a-4d16-9999-a5626c1ba75f.png) 官网示例没有问题的，https://www.surely.cool/doc/selection#row-selection
> 
> 可以看下示例，如果还有问题，可以提交一个在线示例

很抱歉没有提供在线示例，在本地写了个demo，还是能复现出来的，只是将数据改为父子结构，且子不允许选择。代码如下：

`<template>
  <s-table
    :columns="[{ title: ‘名称', dataIndex: 'name' }]"
    rowKey="id"
    :dataSource="dataSource"
    size="small"
    :row-selection="rowSelection"
    defaultExpandAllRows
  >
  </s-table>
</template>
<script setup lang="tsx">
const dataSource = ref([
  { id: 1, name: '001', children: [{ id: 2, name: '001-1' }] },
  { id: 3, name: '002', children: [{ id: 4, name: '002-1' }] },
]);
const rowSelection: STableProps['rowSelection'] = {
  checkStrictly: false,
  onChange: (selectedRowKeys: string[], selectedRows: DataType[]) => {
    console.log(`selectedRowKeys: ${selectedRowKeys}`, 'selectedRows: ', selectedRows);
  },
  getCheckboxProps: (record: DataType) => ({
    disabled: record.id === 4, // Column configuration not to be checked
  }),
};
</script>`

**Comment by tangjinzhou** [comment]
尽可能是一个在线示例，实在不方便，那也要提供一个可以直接复制粘贴的完整组件，你这个代码片段都不完整，复制过来也无法运行

**Comment by YYDee-0920** [comment]
> 尽可能是一个在线示例，实在不方便，那也要提供一个可以直接复制粘贴的完整组件，你这个代码片段都不完整，复制过来也无法运行

已上传代码，您看这样可以吗？
[https://github.com/surely-vue/table/issues/137#issuecomment-1549629809](url)

**Comment by tangjinzhou** [comment]
update to 3.0.7
