### ISSUE TITLE
chrome 66 。滚动条疯狂抽搐，一直在闪

### ISSUE THREAD

**Issue by Hbllol** [surely-vue/table#140]

**Comment by tangjinzhou** [comment]
麻烦提供更多信息，使用的具体版本，什么系统，windows？mac？ 
以及示例代码，谢谢

另外，你的scroll y 动态计算的 ？猜测是可以调整 scroll y 的计算方法解决，

**Comment by Hbllol** [comment]
<s-table
        v-if="dataSource?.length > 0"
        :columns="columns"
        :pagination="false"
        :row-height="60"
        :xVirtual="false"
        :animate-rows="false"
        :default-expand-all-rows="true"
        :data-source="dataSource"
        :scroll="{ y: 420}"
      >

**Comment by Hbllol** [comment]
`<s-table
        v-if="dataSource?.length > 0"
        :columns="columns"
        :pagination="false"
        :row-height="60"
        :xVirtual="false"
        :animate-rows="false"
        :default-expand-all-rows="true"
        :data-source="dataSource"
        :scroll="{ y: 420}"
      >`

**Comment by Hbllol** [comment]
期待您的回复，谢谢

**Comment by tangjinzhou** [comment]
https://www.surely.cool/test  加了一个示例，并没有复现你的问题，示例代码见：https://github.com/surely-vue/table/blob/feat-antdv%404/src/views/test.vue

你可以直接在这个示例上调整 width、height、y，如果能复现，可以把你调整过的数值截图上传。

如果无法复现，你可以像我一样写一个可以复现问题的示例（提供完整代码，不要copy片段），并构建发出在线 url，我们帮助你排查问题

**Comment by tangjinzhou** [comment]
另外建议你先升级最新版看看有没有问题

**Comment by PengEleven** [comment]
这个是因为自动行高，或者有一列宽度是自适应的之类的。
然后分辨率或者可视距离刚好剩的空间不足但是又多了一点，导致组件计算以为可以撑开，撑开之后又有滚动条。
然后计算有问题，就在那里疯狂抖动。
解决方案：尽量不要自动宽、高。除非你能确定数据不会出现上面的情况。

**Comment by tangjinzhou** [comment]
> 这个是因为自动行高，或者有一列宽度是自适应的之类的。 然后分辨率或者可视距离刚好剩的空间不足但是又多了一点，导致组件计算以为可以撑开，撑开之后又有滚动条。 然后计算有问题，就在那里疯狂抖动。 解决方案：尽量不要自动宽、高。除非你能确定数据不会出现上面的情况。

这个场景修了的，你看上面我给的示例

**Comment by Hbllol** [comment]
你说的对 但这个问题它只在低版本 chrome 表现是这样 正常browser不会出错

**Comment by tangjinzhou** [comment]
> https://www.surely.cool/test 加了一个示例，并没有复现你的问题，示例代码见：https:github.com/surely-vue/table/blob/feat-antdv%404/src/views/test.vue
>
> You can adjust the width, height, and y directly on this example. If it can be reproduced, you can upload a screenshot of your adjusted values.
>
> If it cannot be reproduced, you can write an example that can reproduce the problem like me (provide the complete code, do not copy the fragment), and build and send an online url, we will help you troubleshoot the problem

It's better to provide a reproduction example, I didn't reproduce it under the lower version of chrome> https://www.surely.cool/test 加了一个示例，并没有复现你的问题，示例代码见：https://github.com/surely-vue/table/blob/feat-antdv%404/src/views/test.vue
> 
> 你可以直接在这个示例上调整 width、height、y，如果能复现，可以把你调整过的数值截图上传。
> 
> 如果无法复现，你可以像我一样写一个可以复现问题的示例（提供完整代码，不要copy片段），并构建发出在线 url，我们帮助你排查问题

最好还是能提供个复现示例，我在低版本 chrome下也没复现出来  chrome 66版本

**Comment by tangjinzhou** [comment]
升级到 4.0.7
