### ISSUE TITLE
树形拖拽 设置滚动高度后，拖动二级行元素 向下滚动途中 （滚动距离超出滚动高度）拖拽提示会改变成其他元素

### ISSUE THREAD

**Issue by Dreamer-lzy** [surely-vue/table#147]

**Comment by tangjinzhou** [comment]
没明白啥意思，可以录个屏，详细说说嘛

**Comment by Dreamer-lzy** [comment]
![image](https://github.com/surely-vue/table/assets/75427082/3f65cebc-9875-439e-8742-f3f3be6af65f)
![image](https://github.com/surely-vue/table/assets/75427082/02ec1d53-5300-4dcd-84b3-2404d6ca2dd0)
拖着滚动一段距离 ，提示就会变成别的元素了

**Comment by yang-ruiyuan** [comment]
https://github.com/surely-vue/table/assets/50950785/70082300-e799-4aa5-aeb7-fdcc16549076

这是复现的视频效果

**Comment by yang-ruiyuan** [comment]
https://github.com/surely-vue/table/assets/50950785/c6e0d8fb-6f4d-4c2f-9cc6-7be186f30519
这个是复现的视频

**Comment by tangjinzhou** [comment]
update to 4.0.5

**Comment by Dreamer-lzy** [comment]
好了 ，太给力了！！！

**Comment by tangjinzhou** [comment]
> 好了 ，太给力了！！！

可以联系客服付款了 😃
