### ISSUE TITLE
官网中：2.x版本 组件Tabs 标签页 并不支持 自定义页标签头 无该API

### ISSUE THREAD

**Issue by life2022** [surely-vue/table#151]
<img width="659" alt="image" src="https://github.com/surely-vue/table/assets/48848815/09abfa2e-8a5f-487c-b170-67bfc0a928e7">

无name='renderTabBar'的slot 
<img width="1458" alt="image" src="https://github.com/surely-vue/table/assets/48848815/fd4ccc6b-87af-4d6e-a515-900de813e555">

**Comment by tangjinzhou** [comment]
antdv 问题请到antdv 仓库下提交
