### ISSUE TITLE
关于 bodyCell 的渲染问题

### ISSUE THREAD

**Issue by gongyushun-pacvue** [surely-vue/table#155]
目前每次鼠标悬停在table上的时候，都会触发bodyCell调用，这在虚拟滚动时是必要的。
但是在我司具体业务中有时不要虚拟滚动，而是想全量加载所有数据，在ui上需要统一使用一种table，所以希望可以增加一个小功能配置

希望可以提供一个属性，如果设置为false，就阻止 悬停时触发bodyCell调用。
因为全量加载所有数据时，bodyCell 重复渲染是不必要的，而且这时 bodyCell  的内容通常很复杂，重复渲染引起了页面的性能问题。

我司是surely-vue的旗舰版 Plus用户，希望可以考虑

**Comment by tangjinzhou** [comment]
本来优化了的，后来加了 tooltip，要一直取hoverKey，又降级了，
优化了一个 4.0.8 版本，不过还是会执行 bodyCell，但不会那么多了，只和列的数量相关。
后续会抽出 tooltip优化，才能彻底解决这个问题

**Comment by gongyushun-pacvue** [comment]
好的，辛苦了。
但是还有一个疑问，就是我们一直都是按照V3版本的table封装的业务，如果升级到V4的话，api还是会向下兼容的吧？
