### ISSUE TITLE
单于格的行高是否支持调整

### ISSUE THREAD

**Issue by mizhicangyue** [surely-vue/table#159]
单元格内容比较多，行高撑开之后，样式变形。
强行设定
`.surely-table-cell {
  height: auto !important;
}`
只能让单元格变高，但是实际样式还是很糟

**Comment by tangjinzhou** [comment]
![image](https://github.com/surely-vue/table/assets/6937879/efdf7a44-4b5c-46b2-9da4-9f10a66063d4)
