### ISSUE TITLE
table实例中scrollTop和scrollLeft一直为undefined

### ISSUE THREAD

**Issue by ljf1834** [surely-vue/table#161]
通过ref实例获取滚动位置一直为undefined

**Comment by tangjinzhou** [comment]
什么版本，升级最新版看看

**Comment by ljf1834** [comment]
> 什么版本，升级最新版看看

是最新的版本4.1.0-beta.3

**Comment by ljf1834** [comment]
通过onScroll事件获取dom来拿到scrollTop值，但组件expose出的api为undefined

**Comment by tangjinzhou** [comment]
升级到 4.1.0-beta.4

**Comment by ljf1834** [comment]
> 升级到 4.1.0-beta.4

ok,升级到4.1.0-beta.4后scrollTop、scrollLeft都有值了
