### ISSUE TITLE
Not scrolling to the correct position when set keepalive

### ISSUE THREAD

**Issue by xiaobaiku** [surely-vue/table#164]
复现问题的代码仓库：
https://github.com/xiaobaiku/surely-table-issue.git

环境：
microapp + antdv + surely table

问题：
点击包含surely table的子应用并把x表格滚动条拉到最后，在点击另一个子应用在切回去，这时候surely table会出现空白行

![img](https://github.com/surely-vue/table/assets/31175506/e156cac3-cb64-42c7-8abd-da197c65cc5b)

**Comment by xiaobaiku** [comment]
surely 版本号为3.0.5

**Comment by tangjinzhou** [comment]
update to 4.1.0

**Comment by xiaobaiku** [comment]
有计划在3.x版本修复该问题么？

> update to 4.1.0

**Comment by tangjinzhou** [comment]
不会，
v4 相较于 v3几乎没有破坏性更新，而且性能更高，可以升级下
