### ISSUE TITLE
4.0.10 版本 可控的筛选没有生效

### ISSUE THREAD

**Issue by xiaobaiku** [surely-vue/table#169]
https://surely.cool/doc/filter#reset-filter

从3.0.5，升级到4.0.10筛选功能失效。然后发现官网可控的筛选和排序，筛选功能不生效。
![image](https://github.com/surely-vue/table/assets/31175506/595c4a0a-8d8c-4702-98ac-5c0778db0e77)

**Comment by tangjinzhou** [comment]
升级 4.1.11
