### ISSUE TITLE
关于关闭动画

### ISSUE THREAD

**Issue by lambortao** [surely-vue/table#17]
你好
- 我在 [性能优化](https://www.surely.cool/doc/performance#animate) 中看到有关闭动画的操作，但是在 API 列表中并没有搜到相应的 API，请问这个该如何实现？
- 另外，关闭动画这个 API 会关闭列表上的类 hover 效果吗？现在的效果是鼠标在列表上快速的移动的时候，蓝色的选中效果并不会跟随鼠标快速响应，而是需要鼠标在某条数据上停留一会才会出现 hover 效果，看起来像是加了防抖。这个效果在鼠标快速在列表上滑动的时候会给人一种列表卡顿的错觉，这个有 API 能关闭或者调节响应速度吗？

谢谢。

**Comment by tangjinzhou** [comment]
设置 animateRows = false

**Comment by tangjinzhou** [comment]
hover 的确做了“防抖” 
下个版本增加配置项

**Comment by lambortao** [comment]
> hover 的确做了“防抖” 下个版本增加配置项

收到，谢谢！

**Comment by tangjinzhou** [comment]
update to 2.2.0
