### ISSUE TITLE
切换pageSize时触发了2次table的change事件

### ISSUE THREAD

**Issue by xiaoxiaoyu995** [surely-vue/table#18]
可通过 官方例子 https://www.surely.cool/doc/basic#ajax 查看
在切换 pagesize 时 发出了2个请求

**Comment by tangjinzhou** [comment]
下个版本修复，你可以先判断下是否相等 或者 用 watch 来规避这个问题

**Comment by tangjinzhou** [comment]
update to 2.2.1

**Comment by alpiny** [comment]
2.3.3 这个bug依然存在，官网例子也同样请求两次

**Comment by tangjinzhou** [comment]
update to 2.3.4
