### ISSUE TITLE
个性化单元格时候，自定义属性用方法   移入移出行为啥会一直触发调用方法

### ISSUE THREAD

**Issue by ZzNb0813** [surely-vue/table#19]
<template v-else-if="column.dataIndex === 'sortIndex'">
        <span :data-id="checkedRow(record.k[Object.keys(record.k)[0]])">1</span>
     </template
划入划出行 为啥 会一直触发  checkedRow 该方法

**Comment by tangjinzhou** [comment]
为了性能单元格是一个函数式组件，移入移出会重新render，并获取最新属性
自定义属性的方法应该是个纯函数，不会带来什么问题吧

**Comment by ZzNb0813** [comment]
自定义属性是demo,现在的应用场景是的 checkbox 的checked, 下面是引用的方法
const checkedRow = (value: string | number) => {
    const index = checkedList.value.indexOf(value)
    if (index != -1) {
      return true
    }
    return false
  }
这样一直执行不会出现问题吗？checkedList.value 是个变量
