### ISSUE TITLE
横向 滚动条适配 问题

### ISSUE THREAD

**Issue by ZzNb0813** [surely-vue/table#20]
[https://anflower-1257952327.cos.ap-nanjing.myqcloud.com/issue/7410EA48-1141-4fb0-B8F9-0785628C197A.png](url)

**Comment by tangjinzhou** [comment]
？描述清楚一下吧
你这个图片也打不开

**Comment by ZzNb0813** [comment]
就是 在某些尺寸下表格不该出现横向 滚动条   表格会有横向滚动条.

**Comment by ZzNb0813** [comment]
你们提供文档上  基本用法 - 简单表格    第一个表 在我们这里 就有横向滚动条

**Comment by tangjinzhou** [comment]
浏览器尺寸 2031.200 * 1041.600    ？  尺寸不是整数？

**Comment by tangjinzhou** [comment]
mac ？windows？  chrome?  还是。。。

**Comment by ZzNb0813** [comment]
windows - chrome，

**Comment by tangjinzhou** [comment]
出现小数点，应该是浏览器进行了缩放

下个版本会修复该问题，预计5月中旬

**Comment by tangjinzhou** [comment]
update to 2.3.1
