### ISSUE TITLE
添加自适应高度控制

### ISSUE THREAD

**Issue by yanbowe** [surely-vue/table#35]
可以自适应高度，像vben一样的表格高度自适应，也可以继承父元素高度。
https://vvbin.cn/next/#/comp/table/formTable
https://vvbin.cn/next/#/comp/table/resizeParentHeightTable

**Comment by tangjinzhou** [comment]
这不是组件通过api提供的，外层的样式会直接影响到高度设定
，应该是外层使用者填充 height  或 100%  或 flex 或 计算 等等
