### ISSUE TITLE
'ant-design-vue/lib/style/default.less' wasn't found

### ISSUE THREAD

**Issue by qiuhongxing0825** [surely-vue/table#36]
@antdv-components-entry: if(
  isdefined(@root-entry-name),
  if(@root-entry-name = variable, index-pure, index),
  index
);
@antdv-entry: if(@antdv-components-entry = index, default, variable);
**'ant-design-vue/lib/style/default.less' wasn't found**
dependencies:
    **"@surely-vue/table": "^2.2.2",**
    **"ant-design-vue": "^2.2.8",**
vue.config.js:

  css: {
    loaderOptions: {
      less: {
        lessOptions: {
          javascriptEnabled: true,
        },
      },
    },
  },

**Comment by tangjinzhou** [comment]
update to 2.2.3
