### ISSUE TITLE
请问一下surly-vue依赖的antdv版本最低是多少啊？

### ISSUE THREAD

**Issue by XiaoRIGE** [surely-vue/table#37]
我在现有项目中按文档引入surely-vue,编译后报错@antdv-entry is undefined,想知道是不是因为我的antdv版本问题

vue版本：3.0.0
antdv:2.0.0-beat.9

**Comment by tangjinzhou** [comment]
建议直接 antdv 3 起步，
但是兼容 antdv 2 正式版的，你这个还在beta

另外你这个报错应该和版本也没关系，可能是 less 问题，可以看看这个 https://github.com/surely-vue/table/issues/24#issuecomment-1092362573

**Comment by tangjinzhou** [comment]
antdv2 有个less 问题，已经修复，升级surely 到 2.2.3试试吧

**Comment by XiaoRIGE** [comment]
升级到了你说的版本还是一样的问题，晚点我审计less-loader再试试。
