### ISSUE TITLE
ref获取不到元素

### ISSUE THREAD

**Issue by KongZouXiang** [surely-vue/table#38]
![image](https://user-images.githubusercontent.com/43474763/166095342-eaf54ecb-9452-4a78-908b-5e0f877f30f1.png)
**s-table获取不了，div可以正常获取**

**Comment by tangjinzhou** [comment]
什么需求，现在ref里面已经有了 scrollTo、bodyRef 应该够用了呀

**Comment by LYK990** [comment]
> 什么需求，现在ref里面已经有了 scrollTo、bodyRef 应该够用了呀

现在要对s-table进行二次封装，但是ref拿不到元素节点。是因为你们对ref做了处理了所以才拿不到元素节点吗

**Comment by LYK990** [comment]
> 什么需求，现在ref里面已经有了 scrollTo、bodyRef 应该够用了呀


如果是这样的话，有什么办法能让ref获取到dom节点吗

**Comment by tangjinzhou** [comment]
原生getElementByxxxx
