### ISSUE TITLE
自动行高 滚动过快 行高计算问题

### ISSUE THREAD

**Issue by ZzNb0813** [surely-vue/table#42]
自动行高滚动过快行高计算的不对有啥优化方案呢？
![avatar](https://anflower-1257952327.cos.ap-nanjing.myqcloud.com/issue/bace5cb0c9b71ab616d056f0619c6cb.png)

**Comment by tangjinzhou** [comment]
方便提交个代码不，你这个富文本编辑比较复杂，需要具体定位下

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/reverent-mountain-wqvlfg?file=/src/App.vue  你可以通过这个编辑好之后，复制新的 url 发送到这里

**Comment by tangjinzhou** [comment]
这是解决了 ？
