### ISSUE TITLE
表格行拖动表格数据只更新一次

### ISSUE THREAD

**Issue by IPageBear** [surely-vue/table#45]
表格行拖动时表格数据dataSource中数据的位置只更新一次。第一次拖动行时数据顺序会更新，但是再次拖动行时，数据顺序就不更新了。

**Comment by tangjinzhou** [comment]
https://surely.cool/doc/dragable#drag-row   示例没问题啊 
如果你的有问题们请提供复现示例

**Comment by IPageBear** [comment]
我这边有问题的不是说页面显示，而是dataSource的数据。如下图实例为你提供的连接，只是增加了rowDragEnd方法打印了data的值。data值在第二次拖动时值不改变。
![image](https://user-images.githubusercontent.com/18548524/172383952-d725756b-5915-4bc7-a4c1-d0e6c2258f9f.png)
![image](https://user-images.githubusercontent.com/18548524/172385130-cc66e9ab-0c79-4507-8fb9-0e85dab5c6e6.png)

**Comment by tangjinzhou** [comment]
升级 vue 到 3.2.34+  和 surely 到 2.4.0
