### ISSUE TITLE
自定义单元格的问题

### ISSUE THREAD

**Issue by JobinJia** [surely-vue/table#46]
<img width="775" alt="image" src="https://user-images.githubusercontent.com/9244703/172985347-9a925e98-f7cd-4650-993e-c80dc05ff261.png">
当表格为树形表格时，代码如上图所示，但自定义的结果展示如下图
![image](https://user-images.githubusercontent.com/9244703/172985441-a6f2f177-ceb2-46b6-8e5e-8ff1892cb5e8.png)
可以看到，自定义的单元格并没有占据整个行高。
查看元素可以发现一个button元素

![image](https://user-images.githubusercontent.com/9244703/172985703-cfb042b0-b7fd-4e61-83fc-0fb7289c9ea2.png)

上图描述：
黑色边框为自定义的单元格的高度。可以看到并没有占一行,  不能垂直居中。
dom中，绿色为自定义的dom, 红色为表格自带的一个button 。 但实际上该button 理应只有在当前数据有children属性，且为数组时，才有。

**Comment by tangjinzhou** [comment]
提个可运行的代码示例？

**Comment by JobinJia** [comment]
> 提个可运行的代码示例？

[demo](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-3-2-6-forked-1oolwk?file=/src/demo.vue)

**Comment by tangjinzhou** [comment]
那个button是占位缩进的，把你自定义样式的 width：100% 去掉就好了
