### ISSUE TITLE
customHeaderCell 设置样式backgroundColor无效

### ISSUE THREAD

**Issue by JobinJia** [surely-vue/table#47]
通过 column中配置 customHeaderCell 反回的对象中添加style自定义样式时，部分样式无效。
已测试无效样式
backgroundColor, textAlign

[Demo Link](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-3-2-6-forked-1oolwk?file=/src/demo.vue)

**Comment by tangjinzhou** [comment]
1、虚拟滚动是牺牲了样式的灵活定义的，会有一定的心智成本
2、textAlign 可以直接用 align: ‘left’  替代
3、backgroundColor 不是 backgroudColor   示例里面的单词拼写错误，但是对表头分组不生效，会被具体单元格覆盖，你可以 添加 class，然后用 class 来改变分组表头的样式

**Comment by JobinJia** [comment]
表头分组 添加class 并没有效果。上面的demo更新了

**Comment by tangjinzhou** [comment]
https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-3-2-6-forked-9iwnn3?file=/src/demo.vue
1、scoped css 并不会对这种 css 生效，要么  deep 要么不要 scoped
2、打开控制台查看具体挂载位置，以及覆盖背景色位置
3、css 里 red 不能加引号，这是不合法的

**Comment by JobinJia** [comment]
> https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-3-2-6-forked-9iwnn3?file=/src/demo.vue 1、scoped css 并不会对这种 css 生效，要么 deep 要么不要 scoped 2、打开控制台查看具体挂载位置，以及覆盖背景色位置 3、css 里 red 不能加引号，这是不合法的

了然，感谢： ）
