### ISSUE TITLE
对于展开功能的动画效果

### ISSUE THREAD

**Issue by YongTQ** [surely-vue/table#51]
我尝试使用Surely Table做成了一个在线编辑表格，但是现在对于树形结构的展开，会出现如图的动画效果，出现类似上下交换位置的感觉，官方示例是不存在的，就有点眼花，这种是我代码配置有问题吗？
![STable](https://user-images.githubusercontent.com/69885396/176133805-565b244b-3525-47bb-9e33-2b46eb47c0a7.gif)

**Comment by TengQQQ** [comment]
![STable](https://user-images.githubusercontent.com/69885396/176133997-647c436e-44d3-449a-8245-ff09468b11a3.gif)

**Comment by tangjinzhou** [comment]
你可以使用 animateRows 关闭动画试试

**Comment by TengQQQ** [comment]
> 你可以使用 animateRows 关闭动画试试

非常感谢你及时的回答。是的，关闭动画后是正常的了，但是我写过的样式很多都失效了。因为STable的动画效果让客户感觉很好，所以不希望关闭动画，但是我现在没有思路怎样排查这种类似抖动的问题。

**Comment by tangjinzhou** [comment]
理论上动画不应该影响你的自定义样式，所以是不是有可能你的样式影响了动画

你可以提交一个可运行的代码示例，我们来进一步定位问题

**Comment by tangjinzhou** [comment]
有可能是key是有重复？

**Comment by TengQQQ** [comment]
> 有可能是key是有重复？

key是没有重复的，我是随机生成的guid，我整理一份可运行的代码示例出来，麻烦您了

**Comment by TengQQQ** [comment]
[https://github.com/TengQQQ/OnlineEditTable.git](url)

**Comment by tangjinzhou** [comment]
吓死个人，简易版本单个组件 1500 多行   

不过动画是有待优化的

**Comment by TengQQQ** [comment]
> 吓死个人，简易版本单个组件 1500 多行
> 
> 不过动画是有待优化的

额，其实文件是包含了很多缓存模式下没用的功能，忘记隐藏了，所以比较庞大，不好意思0.0
简易版本是指的是用了缓存模式，隐藏掉了使用时的编辑类型，我表述有问题，失误失误-_-||

我这个显示问题是我自定义样式有问题吗，好像子条目超过两条就抖动，一条时不会

还有一个问题，如果对于我分解时添加的输入框使用focus，就会错误的滚动到一个位置，表格的滚动也会有点问题
需要异步调用才能正常显示
![focus](https://user-images.githubusercontent.com/69885396/176607946-896ace1d-1126-48f4-96a2-1b8cd96c1ae8.gif)
