### ISSUE TITLE
最新的源码npm i后启动失败

### ISSUE THREAD

**Issue by 2016011969sunyifang** [surely-vue/table#53]
不清楚是什么原因 vite/node不兼容？
npm i 后npm run dev 失败 版本2.4.0 
麻烦大大看下
![image](https://user-images.githubusercontent.com/37146715/177073758-935c8a23-ecbe-47ed-a133-88d58adabc99.png)

**Comment by tangjinzhou** [comment]
安装  yarn

**Comment by 2016011969sunyifang** [comment]
好的 我尝试一下

**Comment by 2016011969sunyifang** [comment]
> 安装 yarn

可以了 谢谢

**Comment by 2016011969sunyifang** [comment]
> 安装 yarn

大佬 还有个问题 上头让我调研下这个能否支持5w行数据的树状表格全选单选 是否卡顿 然后考虑采购 加了客服没有回复 能跟我讲一下么

**Comment by 2016011969sunyifang** [comment]
> 安装 yarn

![image](https://user-images.githubusercontent.com/37146715/177076336-bff660f0-4a0d-4515-949e-01a247635334.png)
![image](https://user-images.githubusercontent.com/37146715/177076336-bff660f0-4a0d-4515-949e-01a247635334.png)
da'loda'loa大佬 这两个文件获取不到是因为什么 我看项目里这里确实是空的

**Comment by aibayanyu20** [comment]
在main.ts中吧`@surely-vue/table/style`改成`@surely-vue/table/dist/index.less`

**Comment by 2016011969sunyifang** [comment]
> 在main.ts中吧`@surely-vue/table/style`改成`@surely-vue/table/dist/index.less`

![image](https://user-images.githubusercontent.com/37146715/177097776-847f2d40-ae7c-41f6-b4ae-e004a95b29de.png)
大佬改过了 还是不可以

**Comment by aibayanyu20** [comment]
`yarn add @surely-vue/table`

**Comment by 2016011969sunyifang** [comment]
> > 在main.ts中吧`@surely-vue/table/style`改成`@surely-vue/table/dist/index.less`
> 
> ![image](https://user-images.githubusercontent.com/37146715/177097776-847f2d40-ae7c-41f6-b4ae-e004a95b29de.png) 大佬改过了 还是不可以

他还是回去弄这俩文件

**Comment by aibayanyu20** [comment]
https://github.com/misty-learn/md-learn , 你直接跑我这个吧

**Comment by 2016011969sunyifang** [comment]
> https://github.com/misty-learn/md-learn , 你直接跑我这个吧

我克隆一下  谢谢大佬

**Comment by 2016011969sunyifang** [comment]
> https://github.com/misty-learn/md-learn , 你直接跑我这个吧

![image](https://user-images.githubusercontent.com/37146715/177101755-4e6c21f1-8d0b-4609-a200-da49209f7f95.png)
wo'pao'le'y我跑了一下 貌似是报错了 node版本14

**Comment by 2016011969sunyifang** [comment]
> https://github.com/misty-learn/md-learn , 你直接跑我这个吧

大佬方便留个联系方式么

**Comment by aibayanyu20** [comment]
wx: aibayanyu2022

**Comment by 2016011969sunyifang** [comment]
原来开源的是使用产品的demo 大家如果要使用就要去购买哈~
