### ISSUE TITLE
获取滚动位置

### ISSUE THREAD

**Issue by TengQQQ** [surely-vue/table#54]
想请问下，是否有计划开发“关于增加获取滚动位置或高度”的方法或参数，希望能够两个表切换保持滚动高度不变并能获取到最顶部的行数据。

**Comment by tangjinzhou** [comment]
现在是有 scrollTo、scrollTop 暴露出来的，足够满足了 
不过需要注意，如果有自动高度，  两表切换的时候，scrollTop  并不精准，因为未渲染的高度无法获取 
可以看看这个：https://surely.cool/doc/basic#scroll

**Comment by TengQQQ** [comment]
> 现在是有 scrollTo、scrollTop 暴露出来的，足够满足了 不过需要注意，如果有自动高度， 两表切换的时候，scrollTop 并不精准，因为未渲染的高度无法获取 可以看看这个：https://surely.cool/doc/basic#scroll

哦哦，好的，我看一下，因为我在API中没有看到scrollTop 参数
