### ISSUE TITLE
切换 pageSize 时出现了横向滚动条，再切换又消失了

### ISSUE THREAD

**Issue by vzane** [surely-vue/table#58]
pageSize 切换到 50 和 100 的时候出现横向滚动条，切换会 10 和 20 的时候滚动条消失，不知道是什么原因引起的

**Comment by vzane** [comment]
建议添加虚拟滚动条，这种奇怪的问题可能会自动消失 _-_

**Comment by tangjinzhou** [comment]
当数量多的时候，如果出现了竖向滚动条，横向会变窄，自然会出现横向滚动条
当然，这只是一种可能性，具体原因需要提供在线运行示例进一步确认问题
