### ISSUE TITLE
data-source绑定的数据新增一条，表格不更新

### ISSUE THREAD

**Issue by wjr20138216** [surely-vue/table#62]

**Comment by tangjinzhou** [comment]
注意是否是响应式数据

**Comment by wjr20138216** [comment]
`
                let dataSource = Vue.reactive([]);
                for (let i = 0; i < 10; i++) {
                    dataSource.push({
                        key: i,
                        name: `data ${i}`,
                        age: i + 1,
                        address: `London Park no. ${i}`,
                    });
                }
                setInterval(()=>{
                    dataSource.push({
                        key: Date.now(),
                        name: `data ${Date.now()}`,
                        age: Date.now() + 1,
                        address: `London Park no. ${Date.now()}`,
                    });
                },1000)`
像这样生成的数据放到表格能动态更新吗？我这边一直不能动态更新

**Comment by 15937823** [comment]
问题解决了吗？
