### ISSUE TITLE
rowSelection columnTitle 属性设置为字符串不生效

### ISSUE THREAD

**Issue by yushungong** [surely-vue/table#64]
表头和数据行中的checkbox 都没有出现标题

**Comment by wsxe9988** [comment]
提供下codesandbox  可复现的最小case链接

**Comment by yushungong** [comment]
https://codesandbox.io/s/awesome-elion-mkkylg?file=/src/App.vue

**Comment by yushungong** [comment]
https://codesandbox.io/s/awesome-elion-mkkylg?file=/src/App.vue

**Comment by tangjinzhou** [comment]
升级至 2.4.6
