### ISSUE TITLE
rowSelection selections 自定义选择项 配置项

### ISSUE THREAD

**Issue by yushungong** [surely-vue/table#65]
是否可以增加自定义选择项的选中状态，就是和正常下拉菜单一样选中的项可以出现选中样式。
是否可以保存和修改自定义选择项的选中状态就像正常的下拉菜单一样
![image](https://user-images.githubusercontent.com/82556554/182758276-62f9464b-1fc6-4c06-a714-8e30c8804c7f.png)

**Comment by tangjinzhou** [comment]
不可以，意义不大，
例如勾选了全部之后，用户勾掉了一个，就要被反选，这种全选还好处理，像你截图里面的选择当前页面，翻页后又涉及是否选中问题，你可以等 2.4.6 版本通过自定义 title 完全自定义 

另外 2.4.6 selection.text 也会支持 () => VNode 可以自定义

**Comment by yushungong** [comment]
我其实也是希望有一个完全自定义的入口，只是没找到



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月5日(星期五) 下午2:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [surely-vue/table] rowSelection selections 自定义选择项 配置项 (Issue #65)





 
不可以，意义不大，
 例如勾选了全部之后，用户勾掉了一个，就要被反选，这种全选还好处理，像你截图里面的选择当前页面，翻页后又涉及是否选中问题，你可以等 2.4.6 版本通过自定义 title 完全自定义
 
另外 2.4.6 selection.text 也会支持 () =&gt; VNode 可以自定义
