### ISSUE TITLE
表格横向滚动条问题

### ISSUE THREAD

**Issue by yushungong** [surely-vue/table#67]
当存储 dataSource 的 ref 重新赋值时，会出现本来不应该出现的 x 轴滚动条和竖向的阴影
复现地址：https://codesandbox.io/s/awesome-elion-mkkylg?file=/src/App.vue

**Comment by yushungong** [comment]
![image](https://user-images.githubusercontent.com/82556554/182846604-5cf3c7f3-cadb-4d69-ac18-42a8cbbcd833.png)

**Comment by tangjinzhou** [comment]
下个版本会修复

**Comment by tangjinzhou** [comment]
升级至 2.4.6
