### ISSUE TITLE
#summary 总结行问题

### ISSUE THREAD

**Issue by JSli-GitHub** [surely-vue/table#68]
> 使用<a-table-summary-row>会造成列对应不上 并且未悬浮在下方 而是在最后一列的下方 如下图
![image](https://user-images.githubusercontent.com/54303282/183274133-346f0890-26ae-4dfa-89ed-fb13fef25fba.png)
> 如果使用<s-table-summary-row> 会导致只会显示一行汇总行但行内没有文字 如下图
![image](https://user-images.githubusercontent.com/54303282/183274193-1831618b-8823-4e69-b09b-7f4fbfa1d08b.png)
> 复现代码
``` html
<s-table
    :columns="columns"
    :scroll="{ y: 400 }"
    :pagination="false"
    :data-source="dataSource"
  >
    <template #summary>
      <a-table-summary fixed>
        <a-table-summary-row>
          <a-table-summary-cell>Total</a-table-summary-cell>
          <a-table-summary-cell>
            22222222
          </a-table-summary-cell>
          <a-table-summary-cell>
            22222222
          </a-table-summary-cell>
        </a-table-summary-row>
      </a-table-summary>
    </template>  
  </s-table>
```

**Comment by tangjinzhou** [comment]
`s-table`  `a-table-summary`  ?  不要混用   用 s 就都 s

**Comment by JSli-GitHub** [comment]
> `s-table` `a-table-summary` ? 不要混用 用s就都s
第二张图就是都用的stable  但是只有总结行 里面的文本显示不出来

**Comment by tangjinzhou** [comment]
参考这个 https://codesandbox.io/s/awesome-elion-mkkylg?file=/src/App.vue:358-365  给出复现示例，你可以直接在这个链接里面更改然后保存，发出新的链接
