### ISSUE TITLE
特性需求：10万行数据不分页，应该支持滚动条动态加载数据，未加载部分显示骨架屏，体验会很好

### ISSUE THREAD

**Issue by cayweb778** [surely-vue/table#7]
特性需求：10万行数据不分页，应该支持滚动条动态加载数据，未加载部分显示骨架屏，体验会很好

**Comment by tangjinzhou** [comment]
我们会暴露 触底事件，来动态加载数据，骨架屏会有一些问题：尤其是自定义了背景

不过你可以生成 10 万条空数据，每一个单元格都是空的，比骨架屏体验要好的多吧
