### ISSUE TITLE
onSelectAll返回的第一个参数选中状态永远是false

### ISSUE THREAD

**Issue by JobinJia** [surely-vue/table#70]
[demo](https://codesandbox.io/s/ji-ben-yong-fa-ant-design-vue-3-2-6-forked-lwhyvx?file=/src/demo.vue)

打开demo, 查看控制台, 再点击全部选中的checkbox, 可以看到, 无论是全选或者全不选, 打印出来的永远都是false

**Comment by tangjinzhou** [comment]
下个版本修复
不过 onSelectAll 不推荐使用了，推荐使用 onChange

**Comment by tangjinzhou** [comment]
下个版本修复
不过 onSelectAll 不推荐使用了，推荐使用 onChange

**Comment by JobinJia** [comment]
> 下个版本修复 不过 onSelectAll 不推荐使用了，推荐使用 onChange

okay
