### ISSUE TITLE
同时重置column,dataSource为空,来清空表格时报错

### ISSUE THREAD

**Issue by sola5212** [surely-vue/table#8]
表格数据根据columu dataSource 来进行渲染,现在需要多次提交数据,覆盖之前的数据生成新的表格,
每次提交新数据时清空table,直接将column和dataSource清空会直接报错
错误信息: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'left')

**Comment by sola5212** [comment]
不好意思 已解决...应该是要先删除表格数据,之后才能删除表头的问题

**Comment by tangjinzhou** [comment]
这是个问题，应该支持同时置空   下个版本会修复
