### ISSUE TITLE
列宽度显示异常

### ISSUE THREAD

**Issue by hn7830626** [surely-vue/table#89]
**每列均设置了固定宽度,浏览器均为最新版本谷歌** ;台式电脑基本没有问题 ,笔记本电脑列宽度显示异常,所有列排列在最右边 
正常的:
![1664505468607](https://user-images.githubusercontent.com/42940041/193178378-67ffca3a-ac21-44c1-a7bd-4bf2d189aaef.png)

异常的:![70d3366d63eaa40fa6355312fc85327](https://user-images.githubusercontent.com/42940041/193178268-f8bc5f92-354d-48d7-899f-d591f7107a01.png)

**Comment by tangjinzhou** [comment]
第一列设置下最大宽度

**Comment by tangjinzhou** [comment]
因为你所有列都设置了宽度，当屏幕很宽的时候剩余宽度会做一些分配

**Comment by hn7830626** [comment]
谢谢

**Comment by hn7830626** [comment]
谢谢
