### ISSUE TITLE
vue版本更新至3.2.45以后dev时浏览器console出现报警

### ISSUE THREAD

**Issue by angeltxwh** [surely-vue/table#95]
vue版本更新至3.2.45以后dev时浏览器console出现报警

Unexpected semicolon at the end of 'overflow' style value: 'hidden;' 
Unexpected semicolon at the end of 'overflow' style value: 'initial;' 

经过排查，在index.esm.js中搜索
const y = u.value[v] ? "hidden;" : "initial;";
把引号内分号删除即可，因没有源码所以没法pr

surely-vue/table@2.5.0

**Comment by xiaobaiku** [comment]
我在2.5.0版本也遇到过这个问题，不同的是我把；去掉还是会出现这个问题。


[Vue warn]: Unexpected semicolon at the end of 'overflow' style value: 'hidden;' 
  at <Nl key=1 prefix-cls="surely-table" item= Object  ... > 
  ......
