### ISSUE TITLE
行拖拽 , 拖拽到最底部时会自动滚动高度 , 导致页面元素显示不全

### ISSUE THREAD

**Issue by zhangguixin** [surely-vue/table#97]
400的固定高度 , 元素高度只有141 , 拖拽行到最底部时会自动滚动 , 造成页面元素遮挡
![image](https://user-images.githubusercontent.com/51370053/202836879-eebf171d-497e-4006-9347-8516850f1ea3.png)

**Comment by tangjinzhou** [comment]
https://stackblitz.com/edit/vitejs-vite-w4z27y?file=src%2FDemo1.vue  直接编辑后复制新的链接，提供复现示例吧

**Comment by zhangguixin** [comment]
![image](https://user-images.githubusercontent.com/51370053/202840078-0da29c9b-e9ae-4609-9068-0b6cdcf18e88.png)

**Comment by tangjinzhou** [comment]
最新版 2.5.1 没有问题的

**Comment by zhangguixin** [comment]
> 最新版 2.5.1 没有问题的
> 
> https://stackblitz.com/edit/vitejs-vite-29pwfz?file=src%2Fmain.ts,package.json

再此链接上也可以复现
![image](https://user-images.githubusercontent.com/51370053/202951936-7b56cfef-1e24-4453-be52-ad17af9fa201.png)

**Comment by tangjinzhou** [comment]
?  还有问题  ？

**Comment by zhangguixin** [comment]
依然存在

**Comment by zhangguixin** [comment]
是无法复现吗

**Comment by tangjinzhou** [comment]
加个高度吧，我看是水印引起的，数据很少的时候，高度不够水印显示的
https://stackblitz.com/edit/vitejs-vite-29pwfz?file=src%2Fmain.ts,src%2FDemo1.vue

**Comment by tangjinzhou** [comment]
可以考虑升级到付费版哦 ，😸
